ALTER TABLE announcements
  ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'Normal',
  ADD COLUMN IF NOT EXISTS audience VARCHAR(50) DEFAULT 'All Residents',
  ADD COLUMN IF NOT EXISTS visibility VARCHAR(50) DEFAULT 'Public',
  ADD COLUMN IF NOT EXISTS publish_at DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cover_image VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS send_notification TINYINT(1) DEFAULT 1;
