ALTER TABLE users
  ADD COLUMN IF NOT EXISTS profile_photo VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS date_of_birth DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS phase VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS block VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lot VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS last_login_at DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS email_verified TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS phone_verified TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS security_settings JSON DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS emergency_contact JSON DEFAULT NULL;

CREATE TABLE IF NOT EXISTS login_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  browser VARCHAR(100) DEFAULT NULL,
  os VARCHAR(100) DEFAULT NULL,
  device VARCHAR(100) DEFAULT NULL,
  ip VARCHAR(45) DEFAULT NULL,
  location VARCHAR(150) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);